import copy
from typing import Any, Dict, List


_REQUIRED_FIELDS = {
    "node_type",
    "role",
    "effects",
    "inputs",
    "outputs",
    "preconditions",
    "postconditions",
    "field_behavior",
    "instance_behavior",
    "pairings",
    "repair_hints",
}


def _socket(role: str, socket_type: str = "", value_kind: str = "") -> Dict[str, str]:
    return {"role": role, "socket_type": socket_type, "value_kind": value_kind}


def _record(
    node_type: str,
    *,
    role: str,
    common_use: str,
    effects: List[str],
    inputs: Dict[str, Dict[str, str]],
    outputs: Dict[str, Dict[str, str]],
    preconditions: List[str],
    postconditions: List[str],
    planning_hints: List[str],
    pairings: List[str],
    field_behavior: Dict[str, Any] = None,
    instance_behavior: Dict[str, Any] = None,
    repair_hints: List[str] = None,
) -> Dict[str, Any]:
    return {
        "node_type": node_type,
        "role": role,
        "common_use": common_use,
        "effects": list(effects),
        "inputs": copy.deepcopy(inputs),
        "outputs": copy.deepcopy(outputs),
        "typical_inputs": list(inputs),
        "typical_outputs": list(outputs),
        "preconditions": list(preconditions),
        "postconditions": list(postconditions),
        "field_behavior": copy.deepcopy(field_behavior or {}),
        "instance_behavior": copy.deepcopy(instance_behavior or {}),
        "planning_hints": list(planning_hints),
        "pairings": {"common": list(pairings), "avoid": []},
        "common_pairings": list(pairings),
        "repair_hints": list(repair_hints or []),
    }


SEMANTIC_NODE_RECORDS: Dict[str, Dict[str, Any]] = {
    "NodeGroupInput": _record(
        "NodeGroupInput",
        role="Provides group input geometry and exposed parameters.",
        common_use="Start geometry flow from the modifier input.",
        effects=["source", "group_io"],
        inputs={},
        outputs={"Geometry": _socket("source geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["A Geometry Nodes modifier exists."],
        postconditions=["Input geometry is available to downstream data-flow nodes."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use as the first geometry source in pass-through or modifier-driven graphs."],
        pairings=["NodeGroupOutput", "GeometryNodeJoinGeometry"],
        repair_hints=["Add a group input when no source geometry is available."],
    ),
    "NodeGroupOutput": _record(
        "NodeGroupOutput",
        role="Receives final geometry for the modifier output.",
        common_use="End a Geometry Nodes graph.",
        effects=["output", "group_io"],
        inputs={"Geometry": _socket("final geometry", "NodeSocketGeometry", "geometry")},
        outputs={},
        preconditions=["A final geometry stream exists."],
        postconditions=["The modifier returns generated geometry to Blender."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Ensure exactly one intended final geometry stream reaches group output."],
        pairings=["GeometryNodeJoinGeometry", "GeometryNodeRealizeInstances"],
        repair_hints=["Connect the final geometry output to the group output Geometry input."],
    ),
    "GeometryNodeJoinGeometry": _record(
        "GeometryNodeJoinGeometry",
        role="Combines multiple geometry streams into one output.",
        common_use="Merge generated pieces before sending to group output.",
        effects=["join", "architecture"],
        inputs={"Geometry": _socket("geometry streams", "NodeSocketGeometry", "geometry")},
        outputs={"Geometry": _socket("joined geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["One or more geometry streams exist."],
        postconditions=["Multiple geometry streams become one geometry stream."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use near the end of graphs that combine source and generated geometry."],
        pairings=["NodeGroupOutput", "GeometryNodeInstanceOnPoints"],
        repair_hints=["Use Join Geometry before Group Output when more than one final stream exists."],
    ),
    "GeometryNodeTransform": _record(
        "GeometryNodeTransform",
        role="Applies translation, rotation, and scale to geometry.",
        common_use="Move, rotate, or resize generated geometry streams.",
        effects=["transform", "deform", "architecture"],
        inputs={
            "Geometry": _socket("input geometry", "NodeSocketGeometry", "geometry"),
            "Translation": _socket("translation vector", "NodeSocketVector", "value"),
            "Rotation": _socket("rotation vector", "NodeSocketVector", "value"),
            "Scale": _socket("scale vector", "NodeSocketVector", "value"),
        },
        outputs={"Geometry": _socket("transformed geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Input geometry exists."],
        postconditions=["Geometry transform is applied to the stream."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use before join nodes to arrange generated modules."],
        pairings=["GeometryNodeJoinGeometry", "FunctionNodeRandomValue"],
        repair_hints=["Prefer Set Position when per-element field deformation is requested."],
    ),
    "GeometryNodeSetPosition": _record(
        "GeometryNodeSetPosition",
        role="Offsets point or mesh positions using values or fields.",
        common_use="Warp, lift, or procedurally deform geometry.",
        effects=["deform", "field"],
        inputs={
            "Geometry": _socket("input geometry", "NodeSocketGeometry", "geometry"),
            "Selection": _socket("selection mask", "NodeSocketBool", "field"),
            "Position": _socket("position field", "NodeSocketVector", "field"),
            "Offset": _socket("offset field", "NodeSocketVector", "field"),
        },
        outputs={"Geometry": _socket("deformed geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Input geometry exists.", "Offset or position value can be evaluated in geometry context."],
        postconditions=["Point positions are changed on the geometry stream."],
        field_behavior={"produces_field": False, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": True},
        planning_hints=["Use vector math, random values, or position inputs to drive Offset."],
        pairings=["ShaderNodeVectorMath", "FunctionNodeRandomValue", "GeometryNodeInputPosition"],
        repair_hints=["Insert Realize Instances before Set Position when editing individual instances."],
    ),
    "GeometryNodeDistributePointsOnFaces": _record(
        "GeometryNodeDistributePointsOnFaces",
        role="Creates points on mesh faces for scattering workflows.",
        common_use="Generate point geometry from a surface before instancing.",
        effects=["scatter", "field"],
        inputs={
            "Mesh": _socket("surface mesh", "NodeSocketGeometry", "geometry"),
            "Selection": _socket("scatter mask", "NodeSocketBool", "field"),
            "Density": _socket("point density", "NodeSocketFloat", "field"),
            "Seed": _socket("random seed", "NodeSocketInt", "value"),
        },
        outputs={
            "Points": _socket("distributed points", "NodeSocketGeometry", "geometry"),
            "Normal": _socket("surface normal field", "NodeSocketVector", "field"),
            "Rotation": _socket("surface rotation field", "NodeSocketRotation", "field"),
        },
        preconditions=["Surface mesh geometry exists."],
        postconditions=["Point geometry is available for Instance on Points."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Pair with Instance on Points for scatter requests."],
        pairings=["GeometryNodeInstanceOnPoints", "FunctionNodeRandomValue"],
        repair_hints=["Use a mesh-like source before distributing points on faces."],
    ),
    "GeometryNodeInstanceOnPoints": _record(
        "GeometryNodeInstanceOnPoints",
        role="Places instances on point geometry.",
        common_use="Scatter repeated modules on generated or existing points.",
        effects=["instance", "scatter"],
        inputs={
            "Points": _socket("point geometry", "NodeSocketGeometry", "geometry"),
            "Instance": _socket("geometry to instance", "NodeSocketGeometry", "geometry"),
            "Selection": _socket("point selection", "NodeSocketBool", "field"),
            "Rotation": _socket("instance rotation", "NodeSocketRotation", "field"),
            "Scale": _socket("instance scale", "NodeSocketVector", "field"),
        },
        outputs={"Instances": _socket("instanced geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Point geometry exists.", "Instance source geometry exists."],
        postconditions=["Instances exist on the instance domain."],
        field_behavior={"produces_field": False, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": True, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Realize instances before downstream mesh-only operations."],
        pairings=["GeometryNodeDistributePointsOnFaces", "GeometryNodeRealizeInstances"],
        repair_hints=["Connect point geometry to Points and source geometry to Instance."],
    ),
    "GeometryNodeRealizeInstances": _record(
        "GeometryNodeRealizeInstances",
        role="Converts instances into realized geometry.",
        common_use="Apply downstream mesh operations after instancing.",
        effects=["instance", "realize"],
        inputs={"Geometry": _socket("instanced geometry", "NodeSocketGeometry", "geometry")},
        outputs={"Geometry": _socket("realized geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Geometry may contain instances."],
        postconditions=["Instance geometry is converted to editable geometry."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": True, "requires_realized": False},
        planning_hints=["Insert before Set Position or mesh operations that need unique geometry."],
        pairings=["GeometryNodeInstanceOnPoints", "GeometryNodeJoinGeometry"],
        repair_hints=["Add after Instance on Points when a later mesh operation rejects instances."],
    ),
    "FunctionNodeRandomValue": _record(
        "FunctionNodeRandomValue",
        role="Generates deterministic random values or fields.",
        common_use="Drive varied scale, rotation, color, density, or offsets.",
        effects=["random", "field"],
        inputs={
            "Min": _socket("minimum value", "NodeSocketFloat", "value"),
            "Max": _socket("maximum value", "NodeSocketFloat", "value"),
            "ID": _socket("stable id", "NodeSocketInt", "field"),
            "Seed": _socket("random seed", "NodeSocketInt", "value"),
        },
        outputs={"Value": _socket("random value", "NodeSocketFloat", "field")},
        preconditions=["A random range is available."],
        postconditions=["A deterministic random value or field is available."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Connect to scale, rotation, selection, or offset inputs for variation."],
        pairings=["GeometryNodeInstanceOnPoints", "GeometryNodeSetPosition", "ShaderNodeMath"],
        repair_hints=["Set a seed for deterministic generated graphs."],
    ),
    "ShaderNodeMath": _record(
        "ShaderNodeMath",
        role="Computes scalar math values or scalar fields.",
        common_use="Scale, clamp, compare, or combine numeric values.",
        effects=["field", "selection"],
        inputs={"Value": _socket("numeric value", "NodeSocketFloat", "field")},
        outputs={"Value": _socket("numeric result", "NodeSocketFloat", "field")},
        preconditions=["Numeric value or field exists."],
        postconditions=["Numeric result can drive parameters or boolean comparisons."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use for thresholds, periodic patterns, and index-based selections."],
        pairings=["FunctionNodeRandomValue", "GeometryNodeInputIndex"],
        repair_hints=["Use Vector Math instead when the target socket expects a vector."],
    ),
    "FunctionNodeCompare": _record(
        "FunctionNodeCompare",
        role="Compares values or fields and produces a boolean field.",
        common_use="Turn height, slope, index, or random values into a selection mask.",
        effects=["field", "selection"],
        inputs={
            "A": _socket("left comparison value", "", "field"),
            "B": _socket("right comparison value", "", "value"),
        },
        outputs={"Result": _socket("boolean comparison result", "NodeSocketBool", "field")},
        preconditions=["Comparable values or fields exist."],
        postconditions=["A boolean field is available for Selection sockets."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use before Set Material, Instance on Points, or Delete/Separate style selection inputs."],
        pairings=["GeometryNodeSetMaterial", "GeometryNodeInstanceOnPoints", "ShaderNodeSeparateXYZ"],
        repair_hints=["Feed boolean output into Selection sockets, not geometry sockets."],
    ),
    "ShaderNodeVectorMath": _record(
        "ShaderNodeVectorMath",
        role="Computes vector math values or vector fields.",
        common_use="Build offsets, directions, normals, and vector transforms.",
        effects=["field", "deform"],
        inputs={"Vector": _socket("vector value", "NodeSocketVector", "field")},
        outputs={"Vector": _socket("vector result", "NodeSocketVector", "field")},
        preconditions=["Vector value or field exists."],
        postconditions=["Vector result can drive transforms or position offsets."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use before Set Position for field-driven deformation."],
        pairings=["GeometryNodeSetPosition", "GeometryNodeInputPosition", "GeometryNodeInputNormal"],
        repair_hints=["Use Math instead when the target socket expects a scalar."],
    ),
    "ShaderNodeSeparateXYZ": _record(
        "ShaderNodeSeparateXYZ",
        role="Splits a vector field into scalar X, Y, and Z fields.",
        common_use="Extract height or slope components from position and normal fields.",
        effects=["field", "selection"],
        inputs={"Vector": _socket("vector field", "NodeSocketVector", "field")},
        outputs={
            "X": _socket("x component", "NodeSocketFloat", "field"),
            "Y": _socket("y component", "NodeSocketFloat", "field"),
            "Z": _socket("z component", "NodeSocketFloat", "field"),
        },
        preconditions=["A vector field exists."],
        postconditions=["Scalar components can drive math or comparison nodes."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use Position.Z for height masks and Normal.Z for slope masks."],
        pairings=["GeometryNodeInputPosition", "GeometryNodeInputNormal", "FunctionNodeCompare"],
        repair_hints=["Insert before Compare when a vector field is linked to a scalar comparison."],
    ),
    "GeometryNodeCaptureAttribute": _record(
        "GeometryNodeCaptureAttribute",
        role="Evaluates a field and stores it as an anonymous attribute on geometry.",
        common_use="Preserve values before later geometry changes.",
        effects=["attribute", "field"],
        inputs={
            "Geometry": _socket("input geometry", "NodeSocketGeometry", "geometry"),
            "Value": _socket("field to capture", "NodeSocketFloat", "field"),
        },
        outputs={
            "Geometry": _socket("geometry with captured attribute", "NodeSocketGeometry", "geometry"),
            "Attribute": _socket("captured anonymous attribute", "NodeSocketFloat", "field"),
        },
        preconditions=["Input geometry and field exist in the same evaluation context."],
        postconditions=["A stable anonymous attribute is available downstream."],
        field_behavior={"produces_field": True, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use before deformation when later nodes need original values."],
        pairings=["GeometryNodeSetPosition", "GeometryNodeInputPosition"],
        repair_hints=["Capture attributes before the geometry-changing node that would alter the field context."],
    ),
    "GeometryNodeStoreNamedAttribute": _record(
        "GeometryNodeStoreNamedAttribute",
        role="Stores a named attribute on geometry.",
        common_use="Expose generated data for shading, selection, or later workflows.",
        effects=["attribute", "material"],
        inputs={
            "Geometry": _socket("input geometry", "NodeSocketGeometry", "geometry"),
            "Name": _socket("attribute name", "NodeSocketString", "value"),
            "Value": _socket("value to store", "NodeSocketFloat", "field"),
        },
        outputs={"Geometry": _socket("geometry with named attribute", "NodeSocketGeometry", "geometry")},
        preconditions=["Input geometry exists.", "Attribute name is available."],
        postconditions=["Named attribute is stored on the chosen domain."],
        field_behavior={"produces_field": False, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use when the user asks for later shading or external access."],
        pairings=["GeometryNodeSetMaterial", "ShaderNodeMath"],
        repair_hints=["Use Capture Attribute instead for anonymous internal data flow."],
    ),
    "GeometryNodeSetMaterial": _record(
        "GeometryNodeSetMaterial",
        role="Assigns a material to geometry, optionally using a selection.",
        common_use="Apply generated or existing materials to procedural output.",
        effects=["material", "selection"],
        inputs={
            "Geometry": _socket("input geometry", "NodeSocketGeometry", "geometry"),
            "Selection": _socket("material selection", "NodeSocketBool", "field"),
            "Material": _socket("material", "NodeSocketMaterial", "value"),
        },
        outputs={"Geometry": _socket("materialized geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Input geometry exists.", "Material or material placeholder exists."],
        postconditions=["Geometry has material assignment on selected elements."],
        field_behavior={"produces_field": False, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Place after geometry creation and before final output."],
        pairings=["NodeGroupOutput", "GeometryNodeJoinGeometry", "ShaderNodeMath"],
        repair_hints=["Add a selection field when only part of the geometry should receive the material."],
    ),
    "GeometryNodeInputPosition": _record(
        "GeometryNodeInputPosition",
        role="Provides the current element position as a vector field.",
        common_use="Drive spatial deformation, masks, and gradients.",
        effects=["field", "attribute"],
        inputs={},
        outputs={"Position": _socket("position field", "NodeSocketVector", "field")},
        preconditions=["A field evaluation context exists."],
        postconditions=["Position field is available."],
        field_behavior={"produces_field": True, "consumes_field": False, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use with Vector Math or Separate XYZ for spatial effects."],
        pairings=["GeometryNodeSetPosition", "ShaderNodeVectorMath"],
        repair_hints=["Capture original position before changing geometry if old position is needed later."],
    ),
    "GeometryNodeInputNormal": _record(
        "GeometryNodeInputNormal",
        role="Provides surface normals as a vector field.",
        common_use="Drive slope, facing, and normal-based offsets.",
        effects=["field", "selection"],
        inputs={},
        outputs={"Normal": _socket("normal field", "NodeSocketVector", "field")},
        preconditions=["A geometry context with normals exists."],
        postconditions=["Normal field is available."],
        field_behavior={"produces_field": True, "consumes_field": False, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use for slope masks and normal-aligned deformation."],
        pairings=["ShaderNodeVectorMath", "GeometryNodeSetMaterial"],
        repair_hints=["Use Position instead for height gradients."],
    ),
    "GeometryNodeInputIndex": _record(
        "GeometryNodeInputIndex",
        role="Provides the current element index as an integer field.",
        common_use="Create alternating, modulo, or checker-style selections.",
        effects=["field", "selection"],
        inputs={},
        outputs={"Index": _socket("index field", "NodeSocketInt", "field")},
        preconditions=["A field evaluation context exists."],
        postconditions=["Index field is available."],
        field_behavior={"produces_field": True, "consumes_field": False, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use with Math nodes for every-other or modulo selections."],
        pairings=["ShaderNodeMath", "FunctionNodeRandomValue"],
        repair_hints=["Use ID for stable randomness when topology changes."],
    ),
    "GeometryNodeObjectInfo": _record(
        "GeometryNodeObjectInfo",
        role="Provides geometry or transforms from another object.",
        common_use="Use a Blender object as a procedural source or instance.",
        effects=["source", "instance"],
        inputs={"Object": _socket("source object", "NodeSocketObject", "value")},
        outputs={"Geometry": _socket("object geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Referenced object exists."],
        postconditions=["Object geometry or transform data is available."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": True, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use as an instance source when the request references existing objects."],
        pairings=["GeometryNodeInstanceOnPoints", "GeometryNodeRealizeInstances"],
        repair_hints=["Fall back to generated primitive geometry when no object is referenced."],
    ),
    "GeometryNodeCollectionInfo": _record(
        "GeometryNodeCollectionInfo",
        role="Provides geometry or instances from a Blender collection.",
        common_use="Scatter or assemble modules from a collection.",
        effects=["source", "instance"],
        inputs={"Collection": _socket("source collection", "NodeSocketCollection", "value")},
        outputs={"Geometry": _socket("collection geometry", "NodeSocketGeometry", "geometry")},
        preconditions=["Referenced collection exists."],
        postconditions=["Collection geometry or instances are available."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": True, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use when a request asks to use a set of modules or assets."],
        pairings=["GeometryNodeInstanceOnPoints", "GeometryNodeRealizeInstances"],
        repair_hints=["Fall back to a single generated primitive if collection input is unavailable."],
    ),
    "GeometryNodeMeshCube": _record(
        "GeometryNodeMeshCube",
        role="Generates cube mesh geometry.",
        common_use="Create block, module, wall, or building mass geometry.",
        effects=["source", "architecture"],
        inputs={"Size": _socket("cube size", "NodeSocketVector", "value")},
        outputs={"Mesh": _socket("cube mesh", "NodeSocketGeometry", "geometry")},
        preconditions=["Requested geometry can be approximated as a block."],
        postconditions=["Mesh geometry source is available."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use as a default generated module for architecture prompts."],
        pairings=["GeometryNodeTransform", "GeometryNodeInstanceOnPoints"],
        repair_hints=["Use Mesh Grid for surfaces and terrain instead of solid blocks."],
    ),
    "GeometryNodeMeshLine": _record(
        "GeometryNodeMeshLine",
        role="Generates a line of mesh vertices or edges.",
        common_use="Create repeated positions, floors, or linear modules.",
        effects=["source", "architecture", "field"],
        inputs={
            "Count": _socket("element count", "NodeSocketInt", "value"),
            "Offset": _socket("step offset", "NodeSocketVector", "value"),
        },
        outputs={"Mesh": _socket("line mesh", "NodeSocketGeometry", "geometry")},
        preconditions=["Linear distribution or repetition is requested."],
        postconditions=["Linear geometry source is available."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use with Instance on Points for repeated modules along an axis."],
        pairings=["GeometryNodeInstanceOnPoints", "GeometryNodeTransform"],
        repair_hints=["Use Mesh Grid when repetition is two-dimensional."],
    ),
    "GeometryNodeMeshGrid": _record(
        "GeometryNodeMeshGrid",
        role="Generates a rectangular mesh grid.",
        common_use="Create ground, facade, panel, or terrain surfaces.",
        effects=["source", "architecture", "scatter"],
        inputs={
            "Size X": _socket("x size", "NodeSocketFloat", "value"),
            "Size Y": _socket("y size", "NodeSocketFloat", "value"),
            "Vertices X": _socket("x resolution", "NodeSocketInt", "value"),
            "Vertices Y": _socket("y resolution", "NodeSocketInt", "value"),
        },
        outputs={"Mesh": _socket("grid mesh", "NodeSocketGeometry", "geometry")},
        preconditions=["Surface or grid-like geometry is requested."],
        postconditions=["Planar mesh source is available."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use before Set Position for terrain or facade deformation."],
        pairings=["GeometryNodeSetPosition", "GeometryNodeDistributePointsOnFaces"],
        repair_hints=["Increase resolution when field deformation needs visible detail."],
    ),
    "GeometryNodeExtrudeMesh": _record(
        "GeometryNodeExtrudeMesh",
        role="Extrudes mesh elements to add depth or repeated structure.",
        common_use="Create walls, panels, roofs, and hard-surface relief.",
        effects=["architecture", "deform"],
        inputs={
            "Mesh": _socket("input mesh", "NodeSocketGeometry", "geometry"),
            "Selection": _socket("extrusion selection", "NodeSocketBool", "field"),
            "Offset": _socket("extrusion offset", "NodeSocketVector", "field"),
        },
        outputs={"Mesh": _socket("extruded mesh", "NodeSocketGeometry", "geometry")},
        preconditions=["Mesh geometry exists."],
        postconditions=["Selected mesh elements are extruded."],
        field_behavior={"produces_field": False, "consumes_field": True, "domain_sensitive": True},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": True},
        planning_hints=["Use for architectural depth when a flat grid is not enough."],
        pairings=["GeometryNodeMeshGrid", "GeometryNodeSetMaterial"],
        repair_hints=["Realize instances before extrusion if the input contains instances."],
    ),
    "GeometryNodeCurveToMesh": _record(
        "GeometryNodeCurveToMesh",
        role="Converts curves to mesh using a profile curve.",
        common_use="Create railings, pipes, trims, and path-based geometry.",
        effects=["architecture", "deform"],
        inputs={
            "Curve": _socket("input curve", "NodeSocketGeometry", "geometry"),
            "Profile Curve": _socket("profile curve", "NodeSocketGeometry", "geometry"),
        },
        outputs={"Mesh": _socket("converted mesh", "NodeSocketGeometry", "geometry")},
        preconditions=["Curve geometry and profile geometry exist."],
        postconditions=["Curve path is converted to mesh geometry."],
        field_behavior={"produces_field": False, "consumes_field": False, "domain_sensitive": False},
        instance_behavior={"creates_instances": False, "realizes_instances": False, "requires_realized": False},
        planning_hints=["Use for trims, rails, and path-following structures."],
        pairings=["GeometryNodeJoinGeometry", "GeometryNodeSetMaterial"],
        repair_hints=["Use mesh primitives when no curve source is available."],
    ),
}

CORE_NODE_TYPES = tuple(SEMANTIC_NODE_RECORDS)


def validate_semantic_record(record: Dict[str, Any]) -> bool:
    missing = sorted(_REQUIRED_FIELDS - set(record))
    if missing:
        raise ValueError(f"Semantic record missing required fields: {', '.join(missing)}")
    if not isinstance(record["node_type"], str) or not record["node_type"]:
        raise ValueError("Semantic record node_type must be a non-empty string")
    for list_field in ("effects", "preconditions", "postconditions", "repair_hints"):
        if not isinstance(record[list_field], list):
            raise ValueError(f"Semantic record {record['node_type']} field {list_field} must be a list")
    for dict_field in ("inputs", "outputs", "field_behavior", "instance_behavior", "pairings"):
        if not isinstance(record[dict_field], dict):
            raise ValueError(f"Semantic record {record['node_type']} field {dict_field} must be an object")
    if not record["effects"]:
        raise ValueError(f"Semantic record {record['node_type']} must declare at least one effect")
    return True


def validate_semantic_catalog() -> Dict[str, Any]:
    for record in SEMANTIC_NODE_RECORDS.values():
        validate_semantic_record(record)
    return {
        "record_count": len(SEMANTIC_NODE_RECORDS),
        "node_types": list(SEMANTIC_NODE_RECORDS),
    }


def semantic_record_for_node(node_type: str) -> Dict[str, Any]:
    return copy.deepcopy(SEMANTIC_NODE_RECORDS.get(node_type, {}))


def nodes_for_effect(effect: str) -> List[str]:
    normalized = effect.strip().lower()
    return [
        node_type
        for node_type, record in SEMANTIC_NODE_RECORDS.items()
        if normalized in record.get("effects", [])
    ]


def legacy_semantic_for_node(node_type: str) -> Dict[str, Any]:
    return semantic_record_for_node(node_type)
